### ISSUE TITLE
4o1 unauthorized

### ISSUE THREAD

**Issue by Lelivienne** [EvotecIT/PSWinDocumentation.O365HealthService#1]
when i try to run it i got 4o1 unauthorized. i tried to connect with MSOnline and AzureAD first but didn't help. how does it authorize?

**Comment by PrzemyslawKlys** [comment]
Here's the article how to get App ID and App Key. https://evotec.xyz/preparing-azure-app-registrations-permissions-for-office-365-health-service/

If you don't have a primary domain you can use DirectoryID (from the article as the $Domain parameter.
