### ISSUE TITLE
Get-CimInstance : The specified service does not exist as an installed service.

### ISSUE THREAD

**Issue by MartinKRES** [EvotecIT/PSWinDocumentation.O365HealthService#10]
I'm getting the below error when try to run this script as an Azure runbook:

Get-CimInstance : The specified service does not exist as an installed service. At C:\Modules\User\PSWinDocumentation.O365HealthService\PSWinDocumentation.O365HealthService.psm1:638 char:29 + ... ZoneBias = (Get-CimInstance -ClassName Win32_TimeZone -Verbose:$false ... +

**Comment by PrzemyslawKlys** [comment]
I guess Azure RunBook is not windows, so Win33_TimeZone is not going to work. Needs cross-platform solution, hrmms

**Comment by PrzemyslawKlys** [comment]
Should work correctly now - assuming Get-TimeZone will work, but even if it doesn't - it should just push warning out, not stop

Update-module and run again.

**Comment by MartinKRES** [comment]
I've updated the module and I'm still getting the same error.  Looking in the "Public" folder, there doesn't seem to have been any  changes made to the "Get-Office365Health.ps1" module.

**Comment by PrzemyslawKlys** [comment]
I made it in private function... maybe there are 2 entries

**Comment by PrzemyslawKlys** [comment]
Please retry new version - this time should work
