### ISSUE TITLE
StartTime & EndTime are missing

### ISSUE THREAD

**Issue by tschlagwein** [EvotecIT/PSWinDocumentation.O365HealthService#11]
Hello,

since the version 1.0.0 (from 29.01.2022) the output from StartTime & EndTime is missing.

Is there a change go get them back?

Many greetings,

Thorsten

**Comment by PrzemyslawKlys** [comment]
For which section? And I assume old one isn't working anymore right?

**Comment by tschlagwein** [comment]
For the section Incidents. Yes, the old version does not working anymore.
Likewise I tried v1.0.0 and v1.0.1. But all are without StartTime & EndTime.

**Comment by PrzemyslawKlys** [comment]
I'll add it, this is original message

![image](https://user-images.githubusercontent.com/15063294/151828182-13ddb1d4-972d-4aba-b2dc-08a0f85d6bd8.png)

**Comment by tschlagwein** [comment]
Oh, geat and thank you for your fast service!

**Comment by PrzemyslawKlys** [comment]
new release is out.
