### ISSUE TITLE
WARNING: ConvertFrom-UTCTime

### ISSUE THREAD

**Issue by stiven76** [EvotecIT/PSWinDocumentation.O365HealthService#12]
PS C:\WINDOWS\system32> $O365 = Get-Office365Health -ApplicationID $ApplicationID -ApplicationKey $ApplicationKey -TenantDomain $TenantDomain -ToLocalTime #-Verbose

returned warnings
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - We will update the communication pending additional information by either Tenable or Microsoft.. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - We will update the communication pending additional information by either Tenable or Microsoft.. Skipping conversion...

v 1.0.3

**Comment by stiven76** [comment]
v 1.0.3

**Comment by PrzemyslawKlys** [comment]
While i fixed some time conversions, Microsoft keeps handling this manually. In the place where the date should be they added text "We will update the communication pending additional information by either Tenable or Microsoft". That's not gonna fly.
