### ISSUE TITLE
ConvertFrom-UTCTime - couldn't convert time. [...] Thursday, January 26, 2023 by 1:30 AM UTC.

### ISSUE THREAD

**Issue by mababode** [EvotecIT/PSWinDocumentation.O365HealthService#13]
$AllMessages = Get-Office365Health -ApplicationID $ClientID -ApplicationKey $ClientSecret  -TenantDomain $TenantName

WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Thursday, January 26, 2023 by 1:30 AM UTC.
Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Thursday, January 26, 2023 by 2:30 AM UTC.
Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Thursday, January 26, 2023 by 3:30 AM UTC.
Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Wednesday, January 25, 2023, by 11:40 PM UTC.
Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Tuesday November 29, 2022, at 1:00 AM UTC.

**Comment by PrzemyslawKlys** [comment]
Ye, they are doing this manually. They now added 'by', before it was only at. I also found that there are dates that have wrong day of the week (for example Monday, when it was actually Friday). I'll have a fix for this today.

**Comment by mababode** [comment]
that's good news - thx. Would it be possible to include name of property/field that caused the issue? maybe MS adds some proper datetime/offset field in future.

**Comment by PrzemyslawKlys** [comment]
The dates are entered by hand... depending on who adds it, it's as it is - that's why there are so many mistakes there. Some dates are proper datetimes, and there's no problem in them. For others it seems like the technician just randomizes it.
