### ISSUE TITLE
DateTime issue

### ISSUE THREAD

**Issue by greyjoy1** [EvotecIT/PSWinDocumentation.O365HealthService#2]
```
PS C:\> $O365 = Get-Office365Health -ApplicationID $ApplicationID -ApplicationKey $ApplicationKey -TenantDomain $TenantDomain
Exception calling "Parse" with "1" argument(s): "String was not recognized as a valid DateTime because the day of week was incorrect."
At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation.O365HealthService\0.1\PSWinDocumentation.O365HealthService.psm1:25 char:13
+             [DateTime] $ConvertedTime = [DateTime]::Parse($Time)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

Exception calling "Parse" with "1" argument(s): "The string was not recognized as a valid DateTime. There is an unknown word starting at index 23."
At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation.O365HealthService\0.1\PSWinDocumentation.O365HealthService.psm1:25 char:13
+             [DateTime] $ConvertedTime = [DateTime]::Parse($Time)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException
```

**Comment by PrzemyslawKlys** [comment]
Can you let me know which tenant location you have? I've tested on Europe one.

**Comment by harleykin** [comment]
I'm in United States and am seeing this.

**Comment by PrzemyslawKlys** [comment]
Ok figures. Most likely dates behave differently in US then those I have in my tenant. I'll make a test with two other tenants. I believe I have at least one in the US.

**Comment by Raipel** [comment]
I'm in Europe and see it, too.

**Comment by PrzemyslawKlys** [comment]
Right, Ok, guys. Hold on. Will test this with 3 other tenants I have.

**Comment by PrzemyslawKlys** [comment]
Ok, it seems MS guys changed the date format. It's like they type this stuff manually. I have some working concept. will publish soon after few more tests on the date format.

**Comment by PrzemyslawKlys** [comment]
Please try:

```PowerShell
Update-Module PSWinDocumentation.O365HealthService
```

Run it and let me know the results. I've added a warning so that if the format of date will be wrong, or DateTime conversion fails it will show it like:

```PowerShell
 Write-Warning "ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - $Time. Skipping conversion..."
```

If that happens please give me information what does it says, so I can address this. It shouldn't crash thou so data should be readable.

**Comment by Raipel** [comment]
It worked after the module Update ! Thanks a lot!

**Comment by PookyBeer** [comment]
We are seeing this issue in Australia:
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - 9/29/2021 6:00:00 AM. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Tuesday, May 25, 2021, at 7:00 PM UTC unless our continued investigation identifies additional information. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC.. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC.. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC.. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC.. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC. Skipping conversion...
WARNING: ConvertFrom-UTCTime - couldn't convert time. Please report on GitHub - Friday, May 14th, 2021, at 12:00 AM UTC. Skipping conversion...

**Comment by PookyBeer** [comment]
FWIW, I updated my copy of ConvertFrom-UTCTime to have this:
$NewTime = ($Time -replace ", at" -replace "UTC.*" -replace "at" -replace "(^.+?,)" -replace "th" -replace "st" -replace "nd").Trim()
            If ($NewTime -match "/")
			{
				Try {[DateTime]$ConvertedTime = {[DateTime]::Parse($NewTime,([Globalization.CultureInfo]::CreateSpecificCulture('en-US')))}}

Of course, MS will undoubtedly keep putting in all manner of stupid dates, but....

**Comment by PookyBeer** [comment]
Just another note.  Replace also needed -replace "Augu","August" at the end.  I'm sure it could be done cleaner & smarter with a regex, but just did a quick and dirty.

**Comment by PrzemyslawKlys** [comment]
Does this affect everyone or just Australia?

**Comment by PookyBeer** [comment]
No idea, but I would suspect everyone. If you plug in the dates that popped up in my original error, you'll be able to check them against your time zone. The first one (that has the date in US format), would affect anyone not in the US I imagine.

_Wendy_

19 Oct 2021 5:37:48 pm Przemysław Kłys ***@***.***>:

**Comment by PrzemyslawKlys** [comment]
Ye, I guess that's what you get when you push dates manually as you enter them.

**Comment by PrzemyslawKlys** [comment]
Not a big deal anymore. Rewritten using graph, where most of the dates should be correct with only a problem on when parsing incident post messages - as this is still text parsing.
