### ISSUE TITLE
Error: The remote server returned an error: (400) Bad Request

### ISSUE THREAD

**Issue by McDoMaster** [EvotecIT/PSWinDocumentation.O365HealthService#3]
Hi,

I just tried the module, I started with your tutorial here : https://evotec.xyz/preparing-azure-app-registrations-permissions-for-office-365-health-service/

But I only get a 400 error code.
I tried to create a new key but nothing helps

```Powershell
Get-Office365Health -ApplicationID $app -ApplicationKey $key -TenantDomain 'MyDomain' -Verbose
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' =
root\cimv2,'className' = Win32_TimeZone'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: POST https://login.microsoftonline.com/MyDomain/oauth2/token?api-version=1.0 with -1-byte payload
WARNING: Connect-O365ServiceHealth - Error: The remote server returned an error: (400) Bad Request. ```

**Comment by PrzemyslawKlys** [comment]
Is MyDomain custom domain? onmicrosoft.com domains won't work. You could try using DirectoryID instead of Domain.

**Comment by McDoMaster** [comment]
Oh thanks it works with the DirectoryID, seems like the onmicrosoft domain is not supported anymore..

You should update it on your documentation !

Thanks for that help 👍

**Comment by PrzemyslawKlys** [comment]
I've updated both articles about an alternative for DirectoryID. Thanks!

**Comment by itrippedover** [comment]
Hi, I know this issue is closed, but I just hit the same issue using both the Directory ID and custom domain:
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_TimeZone'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: POST https://login.microsoftonline.com/Liquigas/oauth2/token?api-version=1.0 with -1-byte payload
WARNING: Connect-O365ServiceHealth - Error: The remote server returned an error: (400) Bad Request.

The Azure permissions were setup about an hour ago, is there a certain amount of time to wait for this to take effect?

**Comment by PrzemyslawKlys** [comment]
Do be honest I don't remember. Review permissions, if it still doesn't work in like an hour I guess I should verify if Microsoft didn't change something.

**Comment by itrippedover** [comment]
They may well have, I had another script to get service health which in the last month has started returning only a couple of entries when I know there should be 30 or more. So I thought I'd try your script to see if I got a different result.

Permissions are as documented in your article:
![image](https://user-images.githubusercontent.com/58403027/69920550-5fc8f980-14ee-11ea-8ac6-5643a22f2d52.png)

**Comment by itrippedover** [comment]
Will try in a while and let you know :-)

**Comment by PrzemyslawKlys** [comment]
It seems to work for my tenant.

**Comment by PrzemyslawKlys** [comment]
just so you know I noticed the name of your domain may be wrong. It's a full custom domain name or DirectoryID. Unless you did replace the original value for log purposes the $TenantDomain should be your custom domain such as evotec.xyz or directory id.

**Comment by itrippedover** [comment]
Apologies, I had been trying a number of combinations before posting about it

**Comment by itrippedover** [comment]
Ok, not getting the error message now so that’s good. Instead I get no results at all. Fun times!

**Comment by itrippedover** [comment]
Ok, so I’m an idiot. Somehow I put in the wrong Application ID. It works wonderfully now, thankyou for your patience with me 😊

**Comment by PrzemyslawKlys** [comment]
Glad it works :-)
