### ISSUE TITLE
"Extended" misspelled

### ISSUE THREAD

**Issue by MitchellVanHorn** [EvotecIT/PSWinDocumentation.O365HealthService#4]
The object returned from the Get-Office365Health cmdlet should return ServicesExte<b>nd</b>ed, not ServicesExte<b>ned</b>ed.

(By the way, awesome module. Thanks for posting.)

**Comment by PrzemyslawKlys** [comment]
It seems I've actually misspelled it everywhere. Fixing.

**Comment by PrzemyslawKlys** [comment]
```
Update-Module PSWinDocumentation.O365HealthService
```

Thank you!
