### ISSUE TITLE
Line 301 still has an "Exteneded" variable

### ISSUE THREAD

**Issue by MitchellVanHorn** [EvotecIT/PSWinDocumentation.O365HealthService#5]
Line 301 has a variable still called "Exteneded". Didn't find other occurrences in module. Unable to test, but likely breaks Messages related to PlannedMaintenance.

**Comment by PrzemyslawKlys** [comment]
Thanks. I should have done better job. 

Anyways, I still need to get into place where maintenance will be displayed. It probably needs some work, but as I've not seen how this looks like, it's hard to provide proper data.

**Comment by PrzemyslawKlys** [comment]
```
Update-Module PSWinDocumentation.O365health
```
