### ISSUE TITLE
DataTable warning: table id=DT-FelhGYkd 

### ISSUE THREAD

**Issue by wpiotrw** [EvotecIT/PSWinDocumentation.O365HealthService#7]
HEllo

I am using 0365HEALTHservie module to create SERIVCE HEALTH DASHBOARD for our environment.
Following: https://evotec.xyz/getting-azure-health-parsing-html-website-using-psparsehtml/
(section: Merging both dashboards....) but experiencing error shown on the screenshot attached.

![obraz](https://user-images.githubusercontent.com/37083541/83010632-d61b6400-a018-11ea-887d-fd6b92d5d3ba.png)

Any idea?

**Comment by PrzemyslawKlys** [comment]
Closing as you opened it here: https://github.com/EvotecIT/PSWriteHTML/issues/126 as well. It's not related to this module either.
