### ISSUE TITLE
WARNING: Get-Office365ServiceHealthMessages - Error: The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by mohnish-rajpal** [EvotecIT/PSWinDocumentation.O365HealthService#8]
Getting below Error, I have verified that the secret has not expired also the "ServiceHealth.Read" permission is provided with admin consent in Azure Ad. Please help to get this fixed.

PS D:\>Import-Module PSWinDocumentation.O365HealthService -Force
    $ApplicationID = '725XXXXXXXXXXXXXXXXXX'
    $ApplicationKey = 'bXXXXXXXXXXXXXXXXXX'
    $TenantDomain = '92XXXXXXXXXXXXXXXXXX'
    $O365 = Get-Office365Health -ApplicationID $ApplicationID -ApplicationKey $ApplicationKey -TenantDomain $TenantDomain
    $O365.CurrentStatus | Format-Table -AutoSize

WARNING: Get-Office365ServiceHealthServices - Error: The remote server returned an error: (403) Forbidden.
WARNING: Get-Office365ServiceHealthCurrentStatus - Error: The remote server returned an error: (403) Forbidden.
WARNING: Get-Office365ServiceHealthHistoricalStatus - Error: The remote server returned an error: (403) Forbidden.
WARNING: Get-Office365ServiceHealthMessages - Error: The remote server returned an error: (403) Forbidden.

**Comment by PrzemyslawKlys** [comment]
Sorry - I can see the same error. Need to investigate what changed.

**Comment by PrzemyslawKlys** [comment]
> The legacy version of the Service Communications API that's documented in this article is retired. The service health and communications API in Microsoft Graph is now available, and replaces the Service Communications API. For more information about the new Microsoft Graph API, see Overview for accessing service health and communications through Microsoft Graph.

I guess that explains it. I need to rewrite it with Graph. I'll try to fix it soon enough

**Comment by PrzemyslawKlys** [comment]
The new version will require small updates:

![https://evotec.xyz/wp-content/uploads/2022/01/img_61f59e2b000c3.png](https://evotec.xyz/wp-content/uploads/2022/01/img_61f59e2b000c3.png)

Since there is a change to Graph API some things had to change - generally it works the same, but a bit different data, a bit differently exposed. I've updated examples and I will write a new blog post to cover these changes.

**Comment by mohnish-rajpal** [comment]
Thanks @PrzemyslawKlys for fixing this.
